name: video_selling_multivendor_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  get_storage: 2.1.1
  google_fonts: 6.1.0
  loading_animation_widget: 1.2.0+4
  google_nav_bar: 5.0.6
  cached_network_image: 3.3.0
  liquid_pull_to_refresh: 3.0.1
  lottie: 2.6.0
  google_sign_in: 6.1.5
  logger: 2.0.2+1
  flutter_svg: 2.0.7
  timeago: 3.5.0
  dio: 5.3.3
  uuid: 4.1.0
  dotlottie_loader: 0.0.3
  http: 1.1.0
  shimmer: 3.0.0
  flutter_rating_bar: 4.0.1
  pod_player: 0.2.1
  intl: 0.18.1
  permission_handler: 11.0.1
  image_picker: 1.0.4
  font_awesome_flutter: 10.6.0
  flutter_facebook_auth: 6.0.2
  firebase_auth: 4.14.0
  firebase_core: 2.22.0
  animated_bottom_navigation_bar: 1.3.0
  fl_chart: 0.45.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/anim/
  uses-material-design: true

